<center>
    <img src="https://upload.wikimedia.org/wikipedia/commons/6/68/Logo_FPT_Education.png" width="300" alt="FPT University - Ha Noi"  />
</center>

# Access SQL Database Server using R  

---

**Student name:** Trần Huy Tuấn

---

## Objectives
After completing this lab you will be able to:
- Create connection with SQL Server using RODBC  
- Query data from the table  
- Retrieve the result set into a dataframe  
- Close the database connection  
 
---

## Install and Import `RODBC`
`RODBC API` implements odbc database connectivity with compliant databases where drivers exist on the host system.

Two groups of commands are provided.

odbc* commands implement relatively low level access to the odbc functions of similar name. The odbc* group return -1 in stat on error. Up to 16 connections can be open at once to any combination of dsn/hosts. Columns are limited to 255 chars of non-binary data. The functions where usage is obvious from the name are not described below.

sql* commands are higher level constructs to read, save, copy and manipulate data between data frames and sql tables. In general sql* commands return a data frame on success, or -1/verbose on error depending on the errors parameter.

## Install `RODBC` package if needed

In [9]:
install.packages("RODBC")

Warning message:
"package 'RODBC' is in use and will not be installed"

## Load `RODBC` library

In [10]:
library(RODBC)

When the command above completes, the `RODBC` library is loaded in your notebook.

---

###  Connect to SQL Server
Connecting to SQL database server requires the following information:

- Driver Name
- Server
- Database
- User ID
- User Password

In [11]:
# Connect to SQL Server — update your connection info below
connection_string <- paste(
  "Driver={SQL Server};",
  "Server=localhost\\SQLEXPRESS;",           # <-- Replace this
  "Database=DSR301m;",       # <-- Replace this
  "trusted_connection=yes;",            # Or add UID and PWD if needed
  sep=""
)

connection <- odbcDriverConnect(connection_string)
print("Connected to SQL Server")

[1] "Connected to SQL Server"

---

## Understand the datasets

To complete the assignment problems in this notebook you will be using three datasets that are available on the city of Chicago's Data Portal:

*   Socioeconomic Indicators in Chicago
*   Chicago Public Schools
*   Chicago Crime Data

1. Socioeconomic Indicators in Chicago
This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012.


2. Chicago Public Schools
This dataset shows all school level performance data used to create CPS School Report Cards for the 2011-2012 school year. This dataset is provided by the city of Chicago's Data Portal.

3. Chicago Crime Data
This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2001 to present, minus the most recent seven days.

---

## Download the datasets
This assignment requires you to have these three tables populated with a subset of the whole datasets.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the links below to download and save the datasets (.CSV files):

*   [Socioeconomic Indicators in Chicago](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01)
*   [Chicago Public Schools](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01)
*   [Chicago Crime Data](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01)

---

###  Problem 1
Display the first 5 rows from the Crime table.

In [12]:
# Enter your code below
query <- "SELECT TOP 5 * from dbo.ChicagoCrimeData"
result <- sqlQuery(connection,query)
print(result)

        ID CASE_NUMBER       DATE                    BLOCK IUCR PRIMARY_TYPE
1  3512276    HK587712 2004-08-28       047XX S KEDZIE AVE  890        THEFT
2  3406613    HK456306 2004-06-26 009XX N CENTRAL PARK AVE  820        THEFT
3  8002131    HT233595 2011-04-04       043XX S WABASH AVE  820        THEFT
4  7903289    HT133522 2010-12-30     083XX S KINGSTON AVE  840        THEFT
5 10402076    HZ138551 2016-02-02          033XX W 66TH ST  820        THEFT
                    DESCRIPTION         LOCATION_DESCRIPTION ARREST DOMESTIC
1                 FROM BUILDING           SMALL RETAIL STORE      0        0
2                $500 AND UNDER                        OTHER      0        0
3                $500 AND UNDER NURSING HOME/RETIREMENT HOME      0        0
4 FINANCIAL ID THEFT: OVER $300                    RESIDENCE      0        0
5                $500 AND UNDER                        ALLEY      0        0
  BEAT DISTRICT WARD COMMUNITY_AREA_NUMBER FBICODE X_COORDINATE Y_COORDINATE
1  911        9   14                    58       6      1155838      1873050
2 1112       11   27                    23       6      1152206      1906127
3  221        2    3                    38       6      1177436      1876313
4  423        4    7                    46       6      1194622      1850125
5  831        8   15                    66       6      1155240      1860661
  YEAR LATITUDE LONGITUDE                      LOCATION
1 2004 41.80744 -87.70396   (41.8074405, -87.703955849)
2 2004 41.89828 -87.71641 (41.898279962, -87.716405505)
3 2011 41.81593 -87.62464 (41.815933131, -87.624642127)
4 2010 41.74366 -87.56246 (41.743665322, -87.562462756)
5 2016 41.77346 -87.70648 (41.773455295, -87.706480471)

###  Problem 2
Show the community areas with a hardship index greater than 50.

In [13]:
# Enter your code below
query <- "SELECT * FROM dbo.ChicagoCensusData where HARDSHIP_INDEX > 50"
result <- sqlQuery(connection, query)
print(result)

   COMMUNITY_AREA_NUMBER    COMMUNITY_AREA_NAME PERCENT_OF_HOUSING_CROWDED
1                     14            Albany Park                       11.3
2                     19         Belmont Cragin                       10.8
3                     20                Hermosa                        6.9
4                     23          Humboldt park                       14.8
5                     25                 Austin                        6.3
6                     26     West Garfield Park                        9.4
7                     27     East Garfield Park                        8.2
8                     29         North Lawndale                        7.4
9                     30         South Lawndale                       15.2
10                    31        Lower West Side                        9.6
11                    34          Armour Square                        5.7
12                    36                Oakland                        1.3
13                    37            Fuller Park                        3.2
14                    38        Grand Boulevard                        3.3
15                    40        Washington Park                        5.6
16                    42               Woodlawn                        2.9
17                    43            South Shore                        2.8
18                    44                Chatham                        3.3
19                    46          South Chicago                        4.7
20                    47               Burnside                        6.8
21                    49               Roseland                        2.5
22                    50                Pullman                        1.5
23                    51          South Deering                        4.0
24                    52              East Side                        6.8
25                    53           West Pullman                        3.3
26                    54              Riverdale                        5.8
27                    57         Archer Heights                        8.5
28                    58          Brighton Park                       14.4
29                    59          McKinley Park                        7.2
30                    61               New City                       11.9
31                    62            West Elsdon                       11.1
32                    63              Gage Park                       15.8
33                    65              West Lawn                        5.8
34                    66           Chicago Lawn                        7.6
35                    67         West Englewood                        4.8
36                    68              Englewood                        3.8
37                    69 Greater Grand Crossing                        3.6
38                    71         Auburn Gresham                        4.0
   PERCENT_HOUSEHOLDS_BELOW_POVERTY PERCENT_AGED_16_UNEMPLOYED
1                              19.2                       10.0
2                              18.7                       14.6
3                              20.5                       13.1
4                              33.9                       17.3
5                              28.6                       22.6
6                              41.7                       25.8
7                              42.4                       19.6
8                              43.1                       21.2
9                              30.7                       15.8
10                             25.8                       15.8
11                             40.1                       16.7
12                             39.7                       28.7
13                             51.2                       33.9
14                             29.3                       24.3
15                             42.1                       28.6
16                             30.7                       23.4
17                             31.1                       20.0
18                             27.8                       24.0
19                             29.8                       19.7
20                             33.0                       18.6
21                             19.8                       20.3
22                             21.6                       22.8
23                             29.2                       16.3
24                             19.2                       12.1
25                             25.9                       19.4
26                             56.5                       34.6
27                             14.1                       16.5
28                             23.6                       13.9
29                             18.7                       13.4
30                             29.0                       23.0
31                             15.6                       16.7
32                             23.4                       18.2
33                             14.9                        9.6
34                             27.9                       17.1
35                             34.4                       35.9
36                             46.6                       28.0
37                             29.6                       23.0
38                             27.6                       28.3
   PERCENT_AGED_25_WITHOUT_HIGH_SCHOOL_DIPLOMA PERCENT_AGED_UNDER_18_OR_OVER_64
1                                         32.9                             32.0
2                                         37.3                             37.3
3                                         41.6                             36.4
4                                         35.4                             38.0
5                                         24.4                             37.9
6                                         24.5                             43.6
7                                         21.3                             43.2
8                                         27.6                             42.7
9                                         54.8                             33.8
10                                        40.7                             32.6
11                                        34.5                             38.3
12                                        18.4                             40.4
13                                        26.6                             44.9
14                                        15.9                             39.5
15                                        25.4                             42.8
16                                        16.5                             36.1
17                                        14.0                             35.7
18                                        14.5                             40.3
19                                        26.6                             41.1
20                                        19.3                             42.7
21                                        16.9                             41.2
22                                        13.1                             38.6
23                                        21.0                             39.5
24                                        31.9                             42.8
25                                        20.5                             42.1
26                                        27.5                             51.5
27                                        35.9                             39.2
28                                        45.1                             39.3
29                                        32.9                             35.6
30                                        41.5                             38.9
31                                        37.0                             37.7
32                                        51.5                             38.8
33                                        33.6                             39.6
34                                        31.2                             40.6
35                                        26.3                             40.7
36                                        28.5                             42.5
37                                        16.5                             41.0
38                                        18.5                             41.9
   PER_CAPITA_INCOME HARDSHIP_INDEX
1              21323             53
2              15461             70
3              15089             71
4              13781             85
5              15957             73
6              10934             92
7              12961             83
8              12034             87
9              10402             96
10             16444             76
11             16148             82
12             19252             78
13             10432             97
14             23472             57
15             13785             88
16             18672             58
17             19398             55
18             18881             60
19             16579             75
20             12515             79
21             17949             52
22             20588             51
23             14685             65
24             17104             64
25             16563             62
26              8201             98
27             16134             67
28             13089             84
29             16954             61
30             12765             91
31             15754             69
32             12171             93
33             16907             56
34             13231             80
35             11317             89
36             11888             94
37             17285             66
38             15528             74

###  Problem 3
Find all crimes where the arrest was made.

In [14]:
# Enter your code below
query <- "Select * from dbo.ChicagoCrimeData where ARREST = 1"
result <- sqlQuery(connection, query)
print(result)

          ID CASE_NUMBER       DATE                     BLOCK IUCR
1    4494340    HL793243 2005-12-16       005XX E PERSHING RD  860
2    9902691    HX552797 2014-12-23        076XX S CICERO AVE  860
3    6866556    HR271603 2009-04-16  089XX S STONY ISLAND AVE  860
4   10046030    HY234744 2015-04-24      008XX N MICHIGAN AVE  860
5   11230490    JB151690 2018-02-14        036XX S ARCHER AVE  860
6    1516518     G256545 2001-05-04          045XX S DAMEN AV  820
7    4718689    HM324025 2006-05-01            0000X W ELM ST  860
8    1845995     G662598 2001-11-03          0000X N STATE ST  820
9    6855661    HR261581 2009-04-10         017XX W CERMAK RD  860
10   1340847     G040244 2001-01-19          063XX N NAGLE AV  820
11  11143628    JA503725 2017-11-08       058XX S ASHLAND AVE  820
12   5214424    HM803061 2006-12-31       029XX N ASHLAND AVE  860
13   6980726    HR385117 2009-06-20        076XX S CICERO AVE  860
14   1612358     G376790 2001-06-28          0000X S STATE ST  820
15   2522757    HH869886 2002-12-31         048XX W NORTH AVE  820
16   7646435    HS451246 2010-08-07         023XX W ROSCOE ST  460
17   1353618     G056330 2001-01-27         078XX S SAWYER AV  460
18  10179921    HY368284 2015-08-04           024XX S TROY ST  486
19  10879266    JA188596 2017-03-15           013XX W 49TH PL  454
20   4430638    HL725506 2005-11-09     048XX N FRANCISCO AVE  484
21   3434215    HK498590 2004-07-15       011XX N LA SALLE DR  486
22   8771351    HV445580 2012-08-24        034XX N HALSTED ST  460
23   9337353    HW481295 2013-10-05      016XX S ST LOUIS AVE  486
24   3867425    HL240985 2005-03-18        025XX N HALSTED ST  460
25   9068374    HW213573 2013-03-31  072XX S STONY ISLAND AVE  486
26   9999493    HY189363 2015-03-18          001XX N STATE ST  460
27   6982403    HR387668 2009-06-21           021XX W 63RD ST  460
28   4448011    HL745027 2005-11-19           0000X E 69TH ST  460
29   2584554    HH867007 2002-12-30    040XX W IRVING PARK RD  499
30   2903068    HJ575773 2003-08-20        016XX W MADISON ST  460
31   4766490    HM378171 2006-05-28     044XX S PRINCETON AVE  460
32   6780581    HR195987 2009-03-02           001XX W 75TH ST  497
33  11137994    JA496716 2017-11-02     008XX N WASHTENAW AVE  486
34  11014534    JA344492 2017-07-12          009XX E 132ND PL  486
35  10584429    HZ334220 2016-07-03        023XX W PRATT BLVD  460
36   4249096    HL567458 2005-08-11    066XX S CALIFORNIA AVE 1310
37   9817983    HX467661 2014-10-14         013XX S HOMAN AVE 1320
38   3823238    HL187666 2005-02-17       014XX W CHICAGO AVE 1310
39   1720702     G496261 2001-08-20       057XX S HAMILTON AV 1310
40  11185730    JA560123 2017-12-22     031XX N NEWCASTLE AVE 1310
41   2891261    HJ563089 2003-08-15      109XX S MICHIGAN AVE 1310
42   8652732    HV328581 2012-06-10      137XX S BRAINARD AVE 1811
43   8592856    HV267193 2012-05-02           001XX W 87TH ST 1811
44   2973642    HJ620738 2003-09-10      048XX N WINTHROP AVE 1811
45   2910492    HJ557529 2003-08-12       004XX N LARAMIE AVE 2024
46   7692354    HS498920 2010-09-04  071XX S STONY ISLAND AVE 1811
47   4389244    HL608698 2005-09-13        002XX S WHIPPLE ST 2024
48   1577428     G323273 2001-06-04     007XX S CALIFORNIA AV 2024
49   3530721    HK577020 2004-08-23       016XX W JONQUIL TER 2024
50  10177662    HY365876 2015-08-02           041XX W 87TH ST 1811
51   7502426    HS305355 2010-05-13     035XX S WASHTENAW AVE 1821
52   3225630    HK162357 2004-02-03         047XX W FULTON ST 2014
53   5989011    HN778969 2007-12-26          100XX W OHARE ST 2027
54   8508682    HV185969 2012-03-06       003XX S WESTERN AVE 1811
55   2364511    HH657604 2002-09-19         040XX W WILCOX ST 2027
56   9416016    HW555338 2013-12-02       033XX W FILLMORE ST 2093
57   8594622    HV268708 2012-05-02         042XX N MARINE DR 2032
58   1448800     G170513 2001-03-25         074XX S PAXTON AV 1811
59   9012649    HW160463 2013-02-17      071XX S MICHIGAN AVE 1811
60   5547866    HN355411 2007-05-21          004XX N PINE AVE 2027
61   3248961    HK190723 2004-02-18          055XX S WELLS ST 2024
62   8784049    HV457847 2012-09-02    013XX S CHRISTIANA AVE 1811
63   3830058    HL141298 2005-01-24        011XX W WILSON AVE 1811
64   6884465    HR281750 2009-04-22       084XX S SAGINAW AVE 2027
65   4074763    HL342355 2005-05-08       038XX S ROCKWELL ST 2022
66   9458866    HX112183 2014-01-12      056XX S ARTESIAN AVE 2027
67   2973220    HJ624999 2003-09-12           006XX E 51ST ST 2014
68   3085845    HJ618818 2003-09-13         031XX W FIFTH AVE 2095
69   7185163    HR597126 2009-10-19      059XX S CAMPBELL AVE 1811
70   5753121    HN558484 2007-08-29      079XX S ELIZABETH ST 2022
71   7097303    HR505781 2009-08-27         008XX N HOMAN AVE 2092
72   5715871    HN522324 2007-08-11       051XX S EMERALD AVE 1811
73   5844831    HN647052 2007-10-14        062XX S DREXEL AVE 1811
74   8089415    HT323138 2011-05-31      005XX E MARQUETTE RD 2024
75   9419053    HW562748 2013-12-07        051XX W MADISON ST 1811
76   5925338    HN719188 2007-11-20           048XX S WOOD ST 1811
77   8006283    HT237921 2011-04-06      017XX S HAMILTON AVE 1811
78  10025545    HY215032 2015-04-08      039XX W LEXINGTON ST 2014
79   3349359    HK369511 2004-05-17           013XX W 13TH ST 2095
80   4483436    HL703172 2005-10-29        008XX N KEELER AVE 2092
81   5372669    HM762800 2006-12-08       119XX S PARNELL AVE 2092
82   5561014    HN370211 2007-05-28      008XX W EASTWOOD AVE 1811
83   6780235    HR195962 2009-03-02           039XX W 19TH ST 1811
84   4746425    HM284854 2006-04-11      006XX N RIDGEWAY AVE 2024
85   4031070    HL319228 2005-04-26        009XX N HAMLIN AVE 2017
86   7041136    HR447925 2009-07-25         014XX N AVERS AVE 1811
87   5226574    HM590293 2006-09-09    007XX N MONTICELLO AVE 1811
88   6441121    HP513177 2008-08-14        053XX W ADDISON ST 1811
89   4044725    HL331611 2005-05-02         009XX N LOREL AVE 2014
90   5638846    HN448271 2007-07-05       049XX W MAYPOLE AVE 1811
91   2159382    HH402660 2002-05-28      012XX N LOCKWOOD AVE 1811
92   5625404    HN422493 2007-06-22 078XX S COTTAGE GROVE AVE 1811
93   6186267    HP263901 2008-04-05           033XX W 38TH ST 1811
94   2403623     G577663 2001-09-26        062XX S KEDZIE AVE 2027
95   4374455    HL660560 2005-10-08        058XX S KEELER AVE 4387
96  10015483    HY204891 2015-03-31        011XX N PULASKI RD 4625
97   3305754    HK328402 2004-04-27          026XX E 103RD ST 502P
98  11018984    JA349450 2017-07-15           020XX E 79TH ST 502P
99   2415583    HH692211 2002-10-04       007XX S KENNETH AVE 5002
100  7255767    HR668156 2009-11-30           006XX W 61ST ST 4387
101  9426342    HW569852 2013-12-11        0000X N WALLER AVE 5002
102  3943561    HL315870 2005-04-24           015XX W 18TH PL  530
103  2620109    HJ222529 2003-03-06        103XX S DOTY AVE E  553
104  5360488    HN213069 2007-03-07      009XX W MARQUETTE RD  560
105 10950230    JA269772 2017-05-18         038XX W MONROE ST 051A
106  2065876    HH106347 2002-01-04   047XX S FORRESTVILLE AV  560
107 10653179    HZ403432 2016-08-23           008XX E 65TH ST 051A
108  3970108    HL330223 2005-05-02       0000X W CHICAGO AVE  560
109  1962624    HH154448 2002-01-28         064XX S PEORIA DR  560
110 11111810    JA462321 2017-10-07         064XX S MORGAN ST  520
111  3395645    HK450946 2004-06-23      026XX N SEMINARY AVE  610
112  1819413     G652158 2001-10-29       035XX W FRANKLIN BL  910
113  5713696    HN519755 2007-08-10         023XX W GRAND AVE 1220
114  3864164    HL239939 2004-12-09          004XX N STATE ST 1206
115  3300223    HK328522 2004-04-27         016XX W HOWARD ST 1220
116  2225484    HH493814 2002-07-07          034XX N CLARK ST 1210
117  1438213     G161722 2001-03-21         011XX W WILSON AV 1210
118  2003966    HH208082 2002-01-29         057XX S CICERO AV 1130
119  4810471    HM422467 2006-06-18       027XX W ARDMORE AVE  320
120  5260944    HN136243 2007-01-21       036XX N WESTERN AVE  320
121  8841511    HV514287 2012-10-11    046XX N SACRAMENTO AVE  320
122  1570987     G326063 2001-06-05       029XX S DEARBORN ST 1350
123  4084479    HL424420 2005-06-16          027XX S STATE ST 1350
124 11056591    JA393243 2017-08-16       094XX S HARVARD AVE 1365
125  7174283    HR585012 2009-10-13           043XX W 79TH ST 1330
126 11106461    JA455629 2017-10-02        079XX S HALSTED ST 1330
127  8693981    HV369974 2012-07-06        062XX S TALMAN AVE 1330
128  5827212    HN637742 2007-10-09        025XX N PULASKI RD 1330
129  9413737    HW557360 2013-12-03          004XX S STATE ST 1330
130  3064175    HJ776916 2003-11-23     003XX S MAPLEWOOD AVE 1350
131  2774880    HJ419340 2003-06-10       031XX S DEARBORN ST 1330
132  2100965    HH329720 2002-04-25           005XX E 36TH PL 1350
133  3081572    HJ804627 2003-12-07          002XX W ADAMS ST 1330
134  1762743     G575031 2001-09-25             0000X W 87 ST 1330
135  1427912     G122095 2001-03-02        039XX N ASHLAND AV 1505
136  5784844    HN595319 2007-09-17          070XX N CLARK ST 1506
137  1553689     G302291 2001-05-25        026XX W MADISON ST 1506
138  1367327     G057394 2001-01-28         046XX S CICERO AV 1513
139  5228794    HM590468 2006-09-09          010XX N STATE ST 1506
140  8789017    HV463112 2012-09-05        0000X N KENTON AVE 1506
141  7357439    HS100098 2010-01-01       070XX S ROCKWELL ST 143B
142  9432406    HW576249 2013-12-18       012XX S KEDVALE AVE 143A
143  3426362    HK485601 2004-07-10         067XX S THROOP ST 143A
144  2269553    HH460583 2002-06-22      021XX N ST LOUIS AVE 143A
145  4965099    HM576559 2006-09-02      087XX S ESCANABA AVE 143A
146  8681171    HV356389 2012-06-27    046XX S LEAMINGTON AVE  470
147  9551405    HX203242 2014-03-29      063XX S EBERHART AVE  470
148  1806896     G635735 2001-10-22      0000X N HERMITAGE AV 2850
149  5176248    HM768251 2006-12-11      076XX S CAMPBELL AVE 1751
150  3588432    HK677648 2004-10-10       022XX N KOSTNER AVE  281
151  6906555    HR314298 2009-05-11           007XX W 49TH PL 1585
152  8169210    HT404326 2011-07-18         023XX N MASON AVE 1562
153  4072241    HL415544 2005-06-12       031XX W FLOURNOY ST 3750
154  6183080    HP265256 2008-04-06        013XX N HUDSON AVE 1661
155  6987751    HR392537 2009-06-24        070XX S TALMAN AVE 1661
156  3987219    HL266884 2005-03-31          024XX N CLARK ST 2210
157  3266814    HK238408 2004-03-13  093XX S STONY ISLAND AVE 2230
158    21149    HW519443 2013-11-03       044XX S RICHMOND ST  110
159 11233321    JB155558 2018-02-16           036XX W 81ST ST 1540
160 10270593    HY458571 2015-10-12       059XX W CHICAGO AVE 1480
161 10626372    HZ378869 2016-08-05           008XX W 76TH ST 1536
162  9608166    HX258445 2014-05-12          010XX N WELLS ST 1900
163  1326195     G021609 2001-01-11       087XX S ESCANABA AV 9901
                         PRIMARY_TYPE
1                               THEFT
2                               THEFT
3                               THEFT
4                               THEFT
5                               THEFT
6                               THEFT
7                               THEFT
8                               THEFT
9                               THEFT
10                              THEFT
11                              THEFT
12                              THEFT
13                              THEFT
14                              THEFT
15                              THEFT
16                            BATTERY
17                            BATTERY
18                            BATTERY
19                            BATTERY
20                            BATTERY
21                            BATTERY
22                            BATTERY
23                            BATTERY
24                            BATTERY
25                            BATTERY
26                            BATTERY
27                            BATTERY
28                            BATTERY
29                            BATTERY
30                            BATTERY
31                            BATTERY
32                            BATTERY
33                            BATTERY
34                            BATTERY
35                            BATTERY
36                    CRIMINAL DAMAGE
37                    CRIMINAL DAMAGE
38                    CRIMINAL DAMAGE
39                    CRIMINAL DAMAGE
40                    CRIMINAL DAMAGE
41                    CRIMINAL DAMAGE
42                          NARCOTICS
43                          NARCOTICS
44                          NARCOTICS
45                          NARCOTICS
46                          NARCOTICS
47                          NARCOTICS
48                          NARCOTICS
49                          NARCOTICS
50                          NARCOTICS
51                          NARCOTICS
52                          NARCOTICS
53                          NARCOTICS
54                          NARCOTICS
55                          NARCOTICS
56                          NARCOTICS
57                          NARCOTICS
58                          NARCOTICS
59                          NARCOTICS
60                          NARCOTICS
61                          NARCOTICS
62                          NARCOTICS
63                          NARCOTICS
64                          NARCOTICS
65                          NARCOTICS
66                          NARCOTICS
67                          NARCOTICS
68                          NARCOTICS
69                          NARCOTICS
70                          NARCOTICS
71                          NARCOTICS
72                          NARCOTICS
73                          NARCOTICS
74                          NARCOTICS
75                          NARCOTICS
76                          NARCOTICS
77                          NARCOTICS
78                          NARCOTICS
79                          NARCOTICS
80                          NARCOTICS
81                          NARCOTICS
82                          NARCOTICS
83                          NARCOTICS
84                          NARCOTICS
85                          NARCOTICS
86                          NARCOTICS
87                          NARCOTICS
88                          NARCOTICS
89                          NARCOTICS
90                          NARCOTICS
91                          NARCOTICS
92                          NARCOTICS
93                          NARCOTICS
94                          NARCOTICS
95                      OTHER OFFENSE
96                      OTHER OFFENSE
97                      OTHER OFFENSE
98                      OTHER OFFENSE
99                      OTHER OFFENSE
100                     OTHER OFFENSE
101                     OTHER OFFENSE
102                           ASSAULT
103                           ASSAULT
104                           ASSAULT
105                           ASSAULT
106                           ASSAULT
107                           ASSAULT
108                           ASSAULT
109                           ASSAULT
110                           ASSAULT
111                          BURGLARY
112               MOTOR VEHICLE THEFT
113                DECEPTIVE PRACTICE
114                DECEPTIVE PRACTICE
115                DECEPTIVE PRACTICE
116                DECEPTIVE PRACTICE
117                DECEPTIVE PRACTICE
118                DECEPTIVE PRACTICE
119                           ROBBERY
120                           ROBBERY
121                           ROBBERY
122                 CRIMINAL TRESPASS
123                 CRIMINAL TRESPASS
124                 CRIMINAL TRESPASS
125                 CRIMINAL TRESPASS
126                 CRIMINAL TRESPASS
127                 CRIMINAL TRESPASS
128                 CRIMINAL TRESPASS
129                 CRIMINAL TRESPASS
130                 CRIMINAL TRESPASS
131                 CRIMINAL TRESPASS
132                 CRIMINAL TRESPASS
133                 CRIMINAL TRESPASS
134                 CRIMINAL TRESPASS
135                      PROSTITUTION
136                      PROSTITUTION
137                      PROSTITUTION
138                      PROSTITUTION
139                      PROSTITUTION
140                      PROSTITUTION
141                 WEAPONS VIOLATION
142                 WEAPONS VIOLATION
143                 WEAPONS VIOLATION
144                 WEAPONS VIOLATION
145                 WEAPONS VIOLATION
146            PUBLIC PEACE VIOLATION
147            PUBLIC PEACE VIOLATION
148            PUBLIC PEACE VIOLATION
149        OFFENSE INVOLVING CHILDREN
150               CRIM SEXUAL ASSAULT
151                       SEX OFFENSE
152                       SEX OFFENSE
153  INTERFERENCE WITH PUBLIC OFFICER
154                          GAMBLING
155                          GAMBLING
156              LIQUOR LAW VIOLATION
157              LIQUOR LAW VIOLATION
158                          HOMICIDE
159                         OBSCENITY
160 CONCEALED CARRY LICENSE VIOLATION
161                  PUBLIC INDECENCY
162          OTHER NARCOTIC VIOLATION
163                 DOMESTIC VIOLENCE
                                       DESCRIPTION
1                                     RETAIL THEFT
2                                     RETAIL THEFT
3                                     RETAIL THEFT
4                                     RETAIL THEFT
5                                     RETAIL THEFT
6                                   $500 AND UNDER
7                                     RETAIL THEFT
8                                   $500 AND UNDER
9                                     RETAIL THEFT
10                                  $500 AND UNDER
11                                  $500 AND UNDER
12                                    RETAIL THEFT
13                                    RETAIL THEFT
14                                  $500 AND UNDER
15                                  $500 AND UNDER
16                                          SIMPLE
17                                          SIMPLE
18                         DOMESTIC BATTERY SIMPLE
19                      AGG PO HANDS NO/MIN INJURY
20                     PRO EMP HANDS NO/MIN INJURY
21                         DOMESTIC BATTERY SIMPLE
22                                          SIMPLE
23                         DOMESTIC BATTERY SIMPLE
24                                          SIMPLE
25                         DOMESTIC BATTERY SIMPLE
26                                          SIMPLE
27                                          SIMPLE
28                                          SIMPLE
29                     AGGRAVATED DOMESTIC BATTERY
30                                          SIMPLE
31                                          SIMPLE
32  AGGRAVATED DOMESTIC BATTERY: OTHER DANG WEAPON
33                         DOMESTIC BATTERY SIMPLE
34                         DOMESTIC BATTERY SIMPLE
35                                          SIMPLE
36                                     TO PROPERTY
37                                      TO VEHICLE
38                                     TO PROPERTY
39                                     TO PROPERTY
40                                     TO PROPERTY
41                                     TO PROPERTY
42                    POSS: CANNABIS 30GMS OR LESS
43                    POSS: CANNABIS 30GMS OR LESS
44                    POSS: CANNABIS 30GMS OR LESS
45                             POSS: HEROIN(WHITE)
46                    POSS: CANNABIS 30GMS OR LESS
47                             POSS: HEROIN(WHITE)
48                             POSS: HEROIN(WHITE)
49                             POSS: HEROIN(WHITE)
50                    POSS: CANNABIS 30GMS OR LESS
51                  MANU/DEL:CANNABIS 10GM OR LESS
52                    MANU/DELIVER: HEROIN (WHITE)
53                                     POSS: CRACK

###  Problem 4
Retrieve all records for crimes that occurred in a park.

In [15]:
# Enter your code below
query <- "
select dbo.ChicagoCrimeData.ID, dbo.ChicagoCrimeData.CASE_NUMBER, dbo.ChicagoCrimeData.DATE , dbo.ChicagoCensusData.COMMUNITY_AREA_NAME 
from dbo.ChicagoCrimeData join dbo.ChicagoCensusData on dbo.ChicagoCrimeData.COMMUNITY_AREA_NUMBER = dbo.ChicagoCensusData.COMMUNITY_AREA_NUMBER 
where dbo.ChicagoCensusData.COMMUNITY_AREA_NAME like '%Park'"
result <- sqlQuery(connection, query)
print(result)

          ID CASE_NUMBER       DATE COMMUNITY_AREA_NAME
1    3512276    HK587712 2004-08-28       Brighton Park
2    3406613    HK456306 2004-06-26       Humboldt park
3   10769475    HZ534771 2016-11-30         Albany Park
4    3121541    HK108680 2003-01-05  West Garfield Park
5   11230490    JB151690 2018-02-14       McKinley Park
6    7125811    HR535632 2009-09-13         Albany Park
7    4273693    HL590300 2005-08-31       Humboldt park
8   11072808    JA412895 2017-08-31       Humboldt park
9    2771112    HJ415128 2003-06-08       McKinley Park
10   8861185    HV534721 2012-10-25        Lincoln Park
11   3637126    HK728309 2004-11-03       Humboldt park
12   2988938    HJ678713 2003-10-07           Gage Park
13   9509922    HX165034 2014-02-25         Morgan Park
14   8134254    HT368471 2011-06-26         Rogers Park
15  10012707    HY202462 2015-03-28        Portage Park
16  10585295    HZ335434 2016-07-03         Irving Park
17   7166946    HR576816 2009-10-07         Albany Park
18   8155450    HT390647 2011-07-10  East Garfield Park
19   4946261    HM556695 2006-08-23       Humboldt park
20   4424181    HL718742 2005-11-06       Humboldt park
21   7002482    HR408597 2009-07-03  East Garfield Park
22   3867425    HL240985 2005-03-18        Lincoln Park
23   2961173    HJ639869 2003-09-19         Fuller Park
24   4044375    HL388623 2005-05-30  West Garfield Park
25   2584554    HH867007 2002-12-30         Irving Park
26   8223830    HT457930 2011-08-20       Humboldt park
27   6016285    HP121474 2008-01-13        Lincoln Park
28   5663639    HN472326 2007-07-17       Humboldt park
29   9589300    HX239866 2014-04-28  East Garfield Park
30   4766490    HM378171 2006-05-28         Fuller Park
31   9116765    HW261668 2013-05-05  West Garfield Park
32   7937542    HT169840 2011-02-18       Brighton Park
33   8388644    HT621306 2011-12-06        Norwood Park
34   7468176    HS269736 2010-04-22           Hyde Park
35   7881407    HT112422 2011-01-09       Brighton Park
36   8921352    HV592346 2012-12-07       Humboldt park
37   7260480    HR674429 2009-12-04           Gage Park
38   4606754    HM200888 2006-02-25        Norwood Park
39   5567780    HN335611 2007-05-11        Portage Park
40  10770065    HZ535494 2016-11-30       Brighton Park
41   4646705    HM244120 2006-03-21         Rogers Park
42   9305467    HW449676 2013-09-13  West Garfield Park
43   2862972    HJ527694 2003-07-29         Irving Park
44   4700014    HM303461 2006-04-20         Irving Park
45   4920006    HM535632 2006-08-10      Jefferson Park
46  10218934    HY405637 2015-09-01           Gage Park
47   4389244    HL608698 2005-09-13  East Garfield Park
48   3530721    HK577020 2004-08-23         Rogers Park
49   7502426    HS305355 2010-05-13       Brighton Park
50   2364511    HH657604 2002-09-19  West Garfield Park
51   4074763    HL342355 2005-05-08       Brighton Park
52   9458866    HX112183 2014-01-12           Gage Park
53   3085845    HJ618818 2003-09-13  East Garfield Park
54   7097303    HR505781 2009-08-27       Humboldt park
55  10025545    HY215032 2015-04-08  West Garfield Park
56   4483436    HL703172 2005-10-29       Humboldt park
57   4746425    HM284854 2006-04-11       Humboldt park
58   4031070    HL319228 2005-04-26       Humboldt park
59   7041136    HR447925 2009-07-25       Humboldt park
60   5226574    HM590293 2006-09-09       Humboldt park
61   6441121    HP513177 2008-08-14        Portage Park
62   6186267    HP263901 2008-04-05       Brighton Park
63   8300838    HT535175 2011-10-08         Albany Park
64   4750131    HM360756 2006-05-19         Rogers Park
65   5448716    HN275969 2007-04-10       Humboldt park
66  10931066    JA246453 2017-04-30       Humboldt park
67   5601454    HN407116 2007-06-15        Portage Park
68  10015483    HY204891 2015-03-31       Humboldt park
69   2415583    HH692211 2002-10-04  West Garfield Park
70  11122168    JA470839 2017-10-13         Avalon Park
71  10493762    HZ234518 2016-04-21       Brighton Park
72   2948095    HJ637197 2003-08-30       Humboldt park
73  10502099    HZ242203 2016-04-27  East Garfield Park
74  10950230    JA269772 2017-05-18  West Garfield Park
75   8533129    HS479338 2010-08-24         Avalon Park
76   8789058    HV462975 2012-09-05           Gage Park
77   8082600    HT315369 2011-05-26  East Garfield Park
78   3395645    HK450946 2004-06-23        Lincoln Park
79   5835389    HN645348 2007-10-12         Irving Park
80   7427845    HS230740 2010-03-19         Irving Park
81   2514430    HH859922 2002-12-25           Hyde Park
82   9556192    HX207970 2014-04-01  West Garfield Park
83   2316019    HH605275 2002-08-25           Gage Park
84   2169996    HH423186 2002-06-06       Brighton Park
85   3300223    HK328522 2004-04-27         Rogers Park
86  11178752    JA550741 2017-12-14         Irving Park
87   6588112    HP661088 2008-11-02       Humboldt park
88   2906269    HJ580490 2003-08-22       Humboldt park
89   8841511    HV514287 2012-10-11         Albany Park
90   3046354    HJ753917 2003-11-12        Portage Park
91   2953056    HJ642080 2003-09-20        Norwood Park
92   2164207    HH405177 2002-05-29  West Garfield Park
93   5784844    HN595319 2007-09-17         Rogers Park
94   4317595    HL611297 2005-09-14           Gage Park
95   4072241    HL415544 2005-06-12  East Garfield Park
96   3987219    HL266884 2005-03-31        Lincoln Park
97     21149    HW519443 2013-11-03       Brighton Park
98     23469    JA359626 2017-07-23         Avalon Park
99   5738893    HN544458 2007-08-22         Avalon Park
100  9094512    HW238778 2013-04-15         Irving Park
101 10625887    HZ378355 2016-08-02      Jefferson Park
102 10840565    JA143710 2017-02-06       Humboldt park

###  Problem 5
Count the number of crimes that occurred each year.

In [16]:
# Enter your code below
query <- "
SELECT YEAR([DATE]) AS Year, COUNT(*) AS CrimeCount 
FROM dbo.ChicagoCrimeData 
GROUP BY YEAR([DATE]) 
ORDER BY Year"
result <- sqlQuery(connection, query)
print(result)

   Year CrimeCount
1  2001         36
2  2002         37
3  2003         42
4  2004         33
5  2005         44
6  2006         30
7  2007         36
8  2008         21
9  2009         43
10 2010         25
11 2011         25
12 2012         30
13 2013         24
14 2014         25
15 2015         23
16 2016         26
17 2017         30
18 2018          3

### Problem 6
Display the top 3 schools with the highest safety score.

In [17]:
# Enter your code below
query <- "
SELECT TOP 3 [NAME_OF_SCHOOL], [SAFETY_SCORE] 
FROM dbo.ChicagoPublicSchools 
ORDER BY [SAFETY_SCORE] DESC"
result <- sqlQuery(connection, query)
print(result)

                                NAME_OF_SCHOOL SAFETY_SCORE
1            Abraham Lincoln Elementary School           99
2      Alexander Graham Bell Elementary School           99
3 Annie Keller Elementary Gifted Magnet School           99

### Problem 7
Show the community areas with the lowest per capita income.

In [18]:
# Enter your code below
query <- "
select TOP 1 [COMMUNITY_AREA_NAME], [COMMUNITY_AREA_NUMBER], [PER_CAPITA_INCOME] 
from dbo.ChicagoCensusData 
ORDER BY [PER_CAPITA_INCOME] ASC"
result <- sqlQuery(connection, query)
print(result)

  COMMUNITY_AREA_NAME COMMUNITY_AREA_NUMBER PER_CAPITA_INCOME
1           Riverdale                    54              8201

### Problem 8
Find the average hardship index per community area.

In [19]:
# Enter your code below
query <- "
select [COMMUNITY_AREA_NUMBER], AVG([HARDSHIP_INDEX]) as AvgHardShip 
from dbo.ChicagoCensusData 
group by [COMMUNITY_AREA_NUMBER]"
result <- sqlQuery(connection, query)
print(result)

   COMMUNITY_AREA_NUMBER AvgHardShip
1                     NA          NA
2                      1          39
3                      2          46
4                      3          20
5                      4          17
6                      5           6
7                      6           5
8                      7           2
9                      8           1
10                     9           8
11                    10          21
12                    11          25
13                    12          11
14                    13          33
15                    14          53
16                    15          35
17                    16          34
18                    17          28
19                    18          50
20                    19          70
21                    20          71
22                    21          42
23                    22          23
24                    23          85
25                    24          10
26                    25          73
27                    26          92
28                    27          83
29                    28          15
30                    29          87
31                    30          96
32                    31          76
33                    32           3
34                    33           7
35                    34          82
36                    35          47
37                    36          78
38                    37          97
39                    38          57
40                    39          26
41                    40          88
42                    41          14
43                    42          58
44                    43          55
45                    44          60
46                    45          41
47                    46          75
48                    47          79
49                    48          38
50                    49          52
51                    50          51
52                    51          65
53                    52          64
54                    53          62
55                    54          98
56                    55          44
57                    56          32
58                    57          67
59                    58          84
60                    59          61
61                    60          43
62                    61          91
63                    62          69
64                    63          93
65                    64          29
66                    65          56
67                    66          80
68                    67          89
69                    68          94
70                    69          66
71                    70          37
72                    71          74
73                    72          12
74                    73          48
75                    74          16
76                    75          30
77                    76          24
78                    77          19

### Problem 9
List all schools located in the community area with the highest poverty percentage.

In [20]:
# Enter your code below
query <- "
select b.NAME_OF_SCHOOL, a.COMMUNITY_AREA_NAME, a.PERCENT_HOUSEHOLDS_BELOW_POVERTY
from dbo.ChicagoCensusData a join dbo.ChicagoPublicSchools b on a.COMMUNITY_AREA_NUMBER = b.COMMUNITY_AREA_NUMBER
where a.PERCENT_HOUSEHOLDS_BELOW_POVERTY = (
	select top 1 PERCENT_HOUSEHOLDS_BELOW_POVERTY
	from dbo.ChicagoCensusData
	order by PERCENT_HOUSEHOLDS_BELOW_POVERTY desc
)
group by a.PERCENT_HOUSEHOLDS_BELOW_POVERTY, a.COMMUNITY_AREA_NAME, b.NAME_OF_SCHOOL
order by a.PERCENT_HOUSEHOLDS_BELOW_POVERTY desc
"
result <- sqlQuery(connection, query)
print(result)

                                         NAME_OF_SCHOOL COMMUNITY_AREA_NAME
1 George Washington Carver Military Academy High School           Riverdale
2               George Washington Carver Primary School           Riverdale
3                      Ira F Aldridge Elementary School           Riverdale
4                  William E B Dubois Elementary School           Riverdale
  PERCENT_HOUSEHOLDS_BELOW_POVERTY
1                             56.5
2                             56.5
3                             56.5
4                             56.5

### Problem 10
Display all crime types that occurred more than 1000 times.

In [21]:
# Enter your code below
query <- "
SELECT PRIMARY_TYPE, COUNT(*) AS CrimeCount
FROM dbo.ChicagoCrimeData
GROUP BY PRIMARY_TYPE
HAVING COUNT(*) > 1000
ORDER BY CrimeCount DESC
"
result <- sqlQuery(connection, query)
print(result)

#NOTE: THERE IS NO OUTPUT SINCE THERE ARE NO CRIMES WITH MORE THAN 1000 RECORDS
#THE ONLY CRIME TYPE WITH MORE THAN 100 RECORDS IS 'THEFT' WITH 106 RECORDS

[1] PRIMARY_TYPE CrimeCount
<0 rows> (or 0-length row.names)

### Close Database Connection

In [22]:
close(connection)

---

## ✅ Summary
In this lab, you:
- Established a connection to a SQL Server database using RODBC
- Queried data from multiple tables
- Retrieved results into dataframes
- Closed the database connection
---

## Submission Reminder:
### Rename your notebook: `class_studentcode`.ipynb
### Example: `AI1906_HE123456`.ipynb
---

**Author**: MaiCV2


## <h3 align="center"> © FPT University. All rights reserved. <h3/>